[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[build.nixpacksPlan.phases.setup]]
nixPkgs = ["cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman", "pkg-config"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]
